apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-clean-arch-service
spec:
  selector:
    app: tech-challenge-clean-arch
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
